name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --nologo -c Release --no-restore
      - name: Test
        run: dotnet test --nologo -c Release --no-build --verbosity normal
